/**
 * Built-in reference lists for preset dropdown field types.
 *
 * All labels are in French (the primary EduLM locale). Stored as flat string
 * arrays — the field-config renderer treats them the same way as a regular
 * `select` with options, so the form layer doesn't need special handling.
 *
 * Update notes:
 *  - Countries follow ISO 3166-1 (193 UN members + 2 observers + a few common
 *    territories).
 *  - Nationalities follow the standard French adjective form (masculine
 *    singular), sorted alphabetically.
 *  - Lebanese regions are the 26 cazas (districts), grouped roughly by
 *    governorate within the file for readability — the exported list is
 *    alphabetically sorted for the dropdown.
 */

// ─── Countries (FR) ───────────────────────────────────────────────────

export const COUNTRIES_FR: string[] = [
  "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre",
  "Angola", "Antigua-et-Barbuda", "Arabie saoudite", "Argentine", "Arménie",
  "Australie", "Autriche", "Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh",
  "Barbade", "Belgique", "Belize", "Bénin", "Bhoutan", "Biélorussie", "Birmanie (Myanmar)",
  "Bolivie", "Bosnie-Herzégovine", "Botswana", "Brésil", "Brunei", "Bulgarie",
  "Burkina Faso", "Burundi", "Cambodge", "Cameroun", "Canada", "Cap-Vert",
  "Centrafrique", "Chili", "Chine", "Chypre", "Colombie", "Comores", "Congo",
  "Congo (République démocratique)", "Corée du Nord", "Corée du Sud", "Costa Rica",
  "Côte d'Ivoire", "Croatie", "Cuba", "Danemark", "Djibouti", "Dominique",
  "Égypte", "El Salvador", "Émirats arabes unis", "Équateur", "Érythrée",
  "Espagne", "Estonie", "Eswatini", "États-Unis", "Éthiopie", "Fidji",
  "Finlande", "France", "Gabon", "Gambie", "Géorgie", "Ghana", "Grèce",
  "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guinée équatoriale",
  "Guyana", "Haïti", "Honduras", "Hongrie", "Île Maurice", "Îles Marshall",
  "Îles Salomon", "Inde", "Indonésie", "Irak", "Iran", "Irlande", "Islande",
  "Israël", "Italie", "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya",
  "Kirghizistan", "Kiribati", "Kosovo", "Koweït", "Laos", "Lesotho", "Lettonie",
  "Liban", "Libéria", "Libye", "Liechtenstein", "Lituanie", "Luxembourg",
  "Macédoine du Nord", "Madagascar", "Malaisie", "Malawi", "Maldives", "Mali",
  "Malte", "Maroc", "Mauritanie", "Mexique", "Micronésie", "Moldavie", "Monaco",
  "Mongolie", "Monténégro", "Mozambique", "Namibie", "Nauru", "Népal",
  "Nicaragua", "Niger", "Nigéria", "Norvège", "Nouvelle-Zélande", "Oman",
  "Ouganda", "Ouzbékistan", "Pakistan", "Palaos", "Palestine", "Panama",
  "Papouasie-Nouvelle-Guinée", "Paraguay", "Pays-Bas", "Pérou", "Philippines",
  "Pologne", "Portugal", "Qatar", "République dominicaine", "République tchèque",
  "Roumanie", "Royaume-Uni", "Russie", "Rwanda", "Saint-Christophe-et-Niévès",
  "Sainte-Lucie", "Saint-Marin", "Saint-Vincent-et-les-Grenadines", "Salvador",
  "Samoa", "Sao Tomé-et-Principe", "Sénégal", "Serbie", "Seychelles",
  "Sierra Leone", "Singapour", "Slovaquie", "Slovénie", "Somalie", "Soudan",
  "Soudan du Sud", "Sri Lanka", "Suède", "Suisse", "Suriname", "Syrie",
  "Tadjikistan", "Tanzanie", "Tchad", "Thaïlande", "Timor oriental", "Togo",
  "Tonga", "Trinité-et-Tobago", "Tunisie", "Turkménistan", "Turquie", "Tuvalu",
  "Ukraine", "Uruguay", "Vanuatu", "Vatican", "Venezuela", "Vietnam", "Yémen",
  "Zambie", "Zimbabwe",
];

// ─── Nationalities (FR, adjective form) ───────────────────────────────

export const NATIONALITIES_FR: string[] = [
  "Afghane", "Albanaise", "Algérienne", "Allemande", "Américaine", "Andorrane",
  "Angolaise", "Antiguaise", "Argentine", "Arménienne", "Australienne",
  "Autrichienne", "Azerbaïdjanaise", "Bahamienne", "Bahreïnienne", "Bangladaise",
  "Barbadienne", "Belge", "Bélizienne", "Béninoise", "Bhoutanaise",
  "Biélorusse", "Birmane", "Bolivienne", "Bosnienne", "Botswanaise",
  "Brésilienne", "Britannique", "Brunéienne", "Bulgare", "Burkinabée", "Burundaise",
  "Cambodgienne", "Camerounaise", "Canadienne", "Cap-Verdienne", "Centrafricaine",
  "Chilienne", "Chinoise", "Chypriote", "Colombienne", "Comorienne", "Congolaise",
  "Coréenne", "Costaricaine", "Croate", "Cubaine", "Danoise", "Djiboutienne",
  "Dominicaine", "Dominiquaise", "Égyptienne", "Émirienne", "Équatorienne",
  "Érythréenne", "Espagnole", "Estonienne", "Eswatinienne", "Éthiopienne",
  "Fidjienne", "Finlandaise", "Française", "Gabonaise", "Gambienne", "Géorgienne",
  "Ghanéenne", "Grecque", "Grenadienne", "Guatémaltèque", "Guinéenne",
  "Guyanienne", "Haïtienne", "Hondurienne", "Hongroise", "Indienne", "Indonésienne",
  "Irakienne", "Iranienne", "Irlandaise", "Islandaise", "Israélienne", "Italienne",
  "Ivoirienne", "Jamaïcaine", "Japonaise", "Jordanienne", "Kazakhstanaise",
  "Kényane", "Kirghize", "Kiribatienne", "Kosovare", "Koweïtienne", "Laotienne",
  "Lesothane", "Lettonne", "Libanaise", "Libérienne", "Libyenne", "Liechtensteinoise",
  "Lituanienne", "Luxembourgeoise", "Macédonienne", "Malaisienne", "Malawienne",
  "Maldivienne", "Malgache", "Malienne", "Maltaise", "Marocaine", "Marshallaise",
  "Mauricienne", "Mauritanienne", "Mexicaine", "Micronésienne", "Moldave",
  "Monégasque", "Mongole", "Monténégrine", "Mozambicaine", "Namibienne",
  "Nauruane", "Néerlandaise", "Néo-Zélandaise", "Népalaise", "Nicaraguayenne",
  "Nigériane", "Nigérienne", "Nord-coréenne", "Norvégienne", "Omanaise",
  "Ougandaise", "Ouzbèke", "Pakistanaise", "Palaosienne", "Palestinienne",
  "Panaméenne", "Papouane", "Paraguayenne", "Péruvienne", "Philippine",
  "Polonaise", "Portugaise", "Qatarienne", "Roumaine", "Russe", "Rwandaise",
  "Saint-Lucienne", "Saint-Marinaise", "Salomonienne", "Salvadorienne", "Samoane",
  "Santoméenne", "Sénégalaise", "Serbe", "Seychelloise", "Sierra-léonaise",
  "Singapourienne", "Slovaque", "Slovène", "Somalienne", "Soudanaise",
  "Sri-Lankaise", "Sud-africaine", "Sud-coréenne", "Sud-soudanaise", "Suédoise",
  "Suisse", "Surinamaise", "Syrienne", "Tadjike", "Tanzanienne", "Tchadienne",
  "Tchèque", "Thaïlandaise", "Timoraise", "Togolaise", "Tonguienne",
  "Trinidadienne", "Tunisienne", "Turkmène", "Turque", "Tuvaluane", "Ukrainienne",
  "Uruguayenne", "Vanuatuane", "Vaticane", "Vénézuélienne", "Vietnamienne",
  "Yéménite", "Zambienne", "Zimbabwéenne",
];

// ─── Lebanese cazas (districts), sorted alphabetically ───────────────

export const LEBANON_REGIONS_FR: string[] = [
  "Aakkar", "Aley", "Baabda", "Baalbek", "Batroun", "Becharré", "Beyrouth",
  "Békaa-Ouest", "Bint Jbeil", "Chouf", "Hasbaya", "Hermel", "Jbeil (Byblos)",
  "Jezzine", "Kesrouan", "Koura", "Marjeyoun", "Matn", "Minieh-Danniyé",
  "Nabatieh", "Rachaya", "Saïda", "Sour (Tyr)", "Tripoli", "Zahlé", "Zgharta",
];

// ─── Lebanese towns/villages by caza ─────────────────────────────────
// Curated lists per caza, focused on populated towns likely to appear in a
// Lebanese school's catchment area. Denser coverage for Beirut + Mount
// Lebanon since most school families are concentrated there. Not exhaustive
// — admins can ask for additions if a family's town is missing.

export const LEBANON_TOWNS_BY_KAZA: Record<string, string[]> = {
  "Aakkar": [
    "Aabboudiyeh",
    "Aain Ez-Zeit",
    "Aain Tinta",
    "Aain Yaaqoub",
    "Aaiyat",
    "Aakkar El-Aatiqa",
    "Aamaret Aakkar",
    "Aamaret El-Baykat",
    "Aamayer",
    "Aamriyet Aakkar",
    "Aandqet",
    "Aaouaainat Aakkar",
    "AAridet Cheikh Zennad",
    "Aarmeh",
    "Aarqa",
    "Aayoun Aakkar",
    "Aayoun El-Ghizlane",
    "Akkar",
    "Baghdadi",
    "Balde WaMazraatBaldeh",
    "Barcha",
    "Bardeh",
    "Bebnine",
    "Beino",
    "Beit Ayoub",
    "Beit El-Haouch",
    "Beit Mellat",
    "Beit Younes",
    "Berbara Aakkar",
    "berqayel",
    "Bezbina",
    "Biret Aakkar",
    "Borj Aakkar",
    "Bqerzla",
    "Bsatine Aakkar",
    "Bzal",
    "Chane",
    "Chaqdouf",
    "Charbila",
    "Cheikh Mohammad",
    "Cheikh Taba",
    "Cheikh Taba Es-Sahl",
    "Cheikh Zennad",
    "Cheikhlar",
    "Chir Hmairine",
    "Daghleh",
    "Dahr Laissine",
    "Daouret Aakkar",
    "Darine",
    "Dayret Nahr El-Kabir",
    "Deir Dalloum",
    "Deir Jannine",
    "Dibbabiyeh",
    "Dinbou",
    "Douair Aadouiyeh",
    "Fnaydeq",
    "Fraydes Aakkar",
    "Ghazayleh",
    "Habchit",
    "Hakour",
    "Halba",
    "Haouchab",
    "Hayssa",
    "Haytla",
    "Hayzouq",
    "Hedd",
    "Hmaireh Aakkar",
    "Hmaiss Aakkar",
    "Hnaider",
    "Hokr Ed-Dahri",
    "Hokr Etti",
    "Hokr Jouret Srar",
    "Houaich",
    "Hrar",
    "Idbil",
    "Ilat",
    "Janine",
    "Jdeidet El-Qaitaa",
    "Jdidet Ej-Joumeh",
    "Jebrayel",
    "Kafr",
    "Karm Aasfour",
    "Kfar Harra",
    "Kfar Melki Aakkar",
    "Kfar Noun",
    "Khalsa",
    "Kharnoubet Aakkar",
    "Khirbet Char",
    "Khirbet Daoud Aakkar",
    "Khirbet Er Remmane",
    "Khreibet Aakkar",
    "Khreibet Ej-Jindi",
    "Kneisset Aakkar",
    "Kneisset Hnaider",
    "Knisseh",
    "Kouachra",
    "Koueikhat",
    "Kroum El-Aarab",
    "Machha",
    "Machta Hammoud",
    "Majdala",
    "Majdel Akkar",
    "Mar Touma",
    "Marlaya Melhem",
    "Massaaoudiyeh",
    "Mazareaa Jabal Akroum",
    "Mazraat Beit Ghattas",
    "Mazraat En-Nahriyeh",
    "Menneaa",
    "Mhammaret",
    "Michmich Aakkar",
    "Mighraq Aakkar",
    "Minyara",
    "Mounjez",
    "Mqaiteaa",
    "Msalla",
    "Mzeihmeh",
    "Nfisseh",
    "Noura Et-Tahta",
    "Ouadi El-Haour",
    "Ouadi El-Jamous",
    "Qaabrine",
    "Qabaait",
    "Qachlaq",
    "Qantarat Aakkar",
    "Qardaf",
    "Qarha Aakkar",
    "Qbaiyat Aakkar",
    "Qboula",
    "Qleiaat Aakkar",
    "Qloud El-Baqieh",
    "Qornet Aakkar",
    "Qoubber Chamra",
    "Qraiyat",
    "Qsair Aakkar",
    "Rahbeh",
    "Rihaniyet Aakkar",
    "Rmah",
    "Rmoul",
    "Saadine",
    "Sadaqa",
    "Saidnaya",
    "Sammaqiyeh",
    "Sammouniyeh",
    "Sayssouq",
    "Semmaqli",
    "Sfaynet El-Qaitaa",
    "Sfinet Ed-Draib",
    "Sindianet Zeidane",
    "Souaisset Aakkar",
    "Srar",
    "Tall Aabbas Ech-Charqi",
    "Tall Aabbas El-Gharbi",
    "Tall Bireh",
    "Tall Hmayra",
    "Tall Meaayan Tall Kiri",
    "Tall Sebaal",
    "Tallet Chattaha",
    "Tikrit",
    "Tleil",
    "Tshea",
    "Zouarib",
    "Zouq El Hosniyeh",
    "Zouq El-Hadara",
    "Zouq El-Hbalsa",
    "Zouq El-Moqachrine",
  ],
  "Aley": [
    "Aabey",
    "Aain Aanoub",
    "Aain Dara",
    "Aain Drafil",
    "Aain Ej-Jdideh Aaley",
    "Aain El Halazoun",
    "Aain Er-Roummaneh Aaley",
    "Aain Ksour",
    "Aain Traz",
    "Aaley",
    "Aaley Bsatine",
    "Aaramoun Aaley",
    "Aaynab",
    "Aaytat",
    "Aazouniyeh",
    "Aley",
    "Amrousieh, Choueifat",
    "Aramoun",
    "Baaouerta",
    "Bayssour Aaley",
    "Bchamoun",
    "Bedghan Oua Ouadi Bedghan",
    "Behouara",
    "Bejjani",
    "Bhamdoun Ed-Dayaa",
    "Bhamdoun El-Mhatta",
    "Bhamdoun Village",
    "Binnay",
    "Bkhichtay",
    "Blaybel",
    "Bmahray",
    "Bmakine",
    "Bou Zrideh",
    "Bserrine",
    "Bsous",
    "Btalloun",
    "Btater",
    "Chanay",
    "Charoun",
    "Chartoun",
    "Chimlane",
    "Choueifat El-Aamrousiyeh",
    "Choueifat El-Oumara",
    "Choueifat El-Quoubbeh",
    "Daqqoun",
    "Deir Qoubel",
    "Dfoun",
    "Douair Er-Remmaneh",
    "El Malaab",
    "Ghaboune",
    "Habramoun",
    "Homs Oua Hama",
    "Houmal",
    "Ighmid",
    "Jisr El Qadi",
    "Kahhaleh",
    "Keyfoun",
    "Kfar Aamay",
    "Kfar Matta",
    "Maasrati",
    "Majdel Baana",
    "Mansouriyet Bhamdoun",
    "Mazraat En-Nahr Aaley",
    "Mchekhti",
    "Mcherfeh",
    "Mejdlaiya",
    "Mrayjat Aaley",
    "Qmatiyeh",
    "Ramlieh",
    "Richmaiya",
    "Rijmeh",
    "Rimhala",
    "Rouayssat En-Naamane",
    "Saoufar",
    "Selfaya",
    "Sirhmoul",
    "Souq El-Gharb",
    "Taazaniyeh",
  ],
  "Baabda": [
    "Aabadiyeh",
    "Aain Mouaffaq",
    "Aaraiya",
    "Aarbaniyeh",
    "Ain el Remaneh",
    "Ain el Rihani",
    "Araya",
    "Arsoun",
    "Baabda",
    "Baalchmay",
    "Bdadoun",
    "Betchay",
    "Bir Hassan",
    "Bmaryam",
    "Bourj el Barajné",
    "Bourj El-Brajneh",
    "Boutchay",
    "Brazilia",
    "Bsaba",
    "Bsaba Baabda",
    "Btekhnay",
    "Btibyat",
    "Bzebdine",
    "Chbaniyeh",
    "Chiah",
    "Chiyah",
    "Chmeisset Baabda",
    "Choueifat",
    "Choueit",
    "Chouit",
    "Deir El-harf",
    "Deir Khouna",
    "Des Officiers",
    "Dlaybeh",
    "Falougha",
    "Furn Ech-Chebbak",
    "Galerie Semaan",
    "Ghobeiry",
    "Hadath",
    "Hadath Beyrouth",
    "Hammana",
    "Haret el Botm",
    "Haret el Sitt",
    "Haret Es-Sit",
    "Haret Hamzeh",
    "Haret Hreik",
    "Hasbaiya El-Matn",
    "Hazmieh - Mar Takla",
    "Hlaliyeh Baabda",
    "Jamhour",
    "Jouar El-Haouz",
    "Jouret Arsoun",
    "Kfar Chima",
    "Kfar Selouane",
    "Kfarchima",
    "Khalouat Baabda",
    "Khreibé",
    "Khreibet Baabda",
    "Kneisset Baabda",
    "Laylakeh",
    "Louayzeh Baabda",
    "Loueizé",
    "Merdache",
    "Mzairaa Baabda",
    "Ouadi Chahrour El Aaoulia",
    "Ouadi Chahrour Es-Soufla",
    "Qalaat Baabda",
    "Qobbayaa",
    "Qordata",
    "Qornayel",
    "Qrayet Baabda",
    "Qsaibeh Baabda",
    "Qtaleh Baabda",
    "Ras El Matn",
    "Ras El-Href",
    "Rouayssrt El-Ballout",
    "Route de Damas",
    "Route Palais Présidentiel",
    "Salima Baabda",
    "Tahouitat El Ghadir",
    "Tarchich",
    "Wadi chahrour",
    "Zandouqa",
    "Zhaimé",
    "Zhaymé",
  ],
  "Baalbek": [
    "Aadous",
    "Aain Baalbek",
    "Aain Bourday",
    "Aain Ej-Jaouz Baalbek",
    "Aain El-Barnaya",
    "Aain Es-Siyaa Chadoura",
    "Aamchki",
    "Aarsal",
    "Aaynata Baalbek",
    "Baalbek",
    "Bajjaje",
    "Barqa",
    "Bechouat",
    "Bednayel Baalbak",
    "Beit Chama",
    "Bouday",
    "Brital",
    "Btedaai",
    "Chaaibeh",
    "Chaat",
    "Chlifa",
    "Chmistar",
    "Dar El-Ouassaa",
    "Deir El-Ahmar",
    "Deir Mar Maroun Baalbek",
    "Douris",
    "Fekehe",
    "Hadath Baalbek",
    "Halbata",
    "Ham",
    "haouch El-Dehab",
    "Haouch En-Nabi",
    "Haouch Er-Rafqa",
    "Haouch Snaid",
    "Haouch Tall Safiyeh",
    "Haouche Barada",
    "Haour Taala",
    "Harabta",
    "Hizzine",
    "Houara",
    "Iaat",
    "Jebaa",
    "Jenta",
    "Kfar Dabach",
    "Kfar Dane",
    "Kharayeb El-Hermel",
    "Khodr Baalbek",
    "Khreibet Baalbek",
    "Kneisset Baalbek",
    "Laboueh",
    "Maaraboun",
    "Majdaloun",
    "Maqneh",
    "Mazraat beit Mchaik",
    "Moqraq",
    "Mousrayeh",
    "Nabha Ed-Damdoum",
    "Nabi Chbay",
    "Nabi Chit",
    "Nabi Osmane",
    "Nahleh baalbek",
    "Ouadi El-Aaoss",
    "Qaa Baalbek",
    "Qaa Baayoun",
    "Qaa Jouar Maqiyé",
    "Qaa Ouadi El-Khanzir",
    "Qarha Baalbek",
    "Qsarnaba",
    "Ram Baalbek",
    "Ras Baalbek Ech-Charqi",
    "Ras Baalbek Es-Sahel",
    "Riha",
    "Saaideh",
    "Sbouba",
    "Serraaine Et-Tahta",
    "Slouqi",
    "Taibet Baalbek",
    "Talia",
    "Taraiya",
    "Temnine El-Faouqa",
    "Temnine Et-Tahta",
    "Tfail",
    "Yahfoufa",
    "Yammouneh",
    "Youmine",
    "Zabboud",
  ],
  "Batroun": [
    "AAbdelli",
    "Aabrine",
    "Aalali",
    "Aartiz",
    "Assia",
    "Basbina",
    "Batroun",
    "Bcheaali",
    "Bechtoudar",
    "Beit Chlala",
    "Beit Kassab",
    "Bijdarfil",
    "Boqsmaiya",
    "Chatine",
    "Chibtine",
    "Chikka",
    "Daael",
    "Dahr Abi Yaghi",
    "Daraya El-Batroun",
    "Deir Billa",
    "Deir Kfifane",
    "Deir Mar Youhanna EL-Batroun",
    "Deir Mar Youssef Jrabta",
    "Douma",
    "Douq",
    "Edde El-Batroun",
    "Ftahat El-Batroun",
    "Ghouma",
    "Hadtoun",
    "Hamat",
    "Harbouna",
    "Hardine",
    "Helta",
    "Heri",
    "Ijdabra",
    "Jebla",
    "Jrabta El-Batroun",
    "Jrane El-Batroun",
    "Kfar Aabida",
    "Kfar Hatna",
    "Kfar Hay",
    "Kfar Hilda",
    "Kfar Khollos",
    "Kfarb Shlaimane",
    "Kfifane",
    "Kfour El-Aarbi",
    "Koubba",
    "Kour",
    "Mar Mama",
    "Masrah",
    "Mehmarch",
    "Mrah Chdid",
    "Mrah El-Hajj",
    "Mrah Ez Ziyat",
    "Nahleh El-Batroun",
    "Niha El-Batroun",
    "Ouajh El-Hajjar",
    "Ouata Houb",
    "Qatnaaoun",
    "Racha",
    "Rachana",
    "Rachkida",
    "Ram El-Batroun",
    "Ras Nahhach",
    "Selaata",
    "Sghar",
    "Smar Jbayl",
    "Sourat El-Batroun",
    "Tannourine El-Faouqa",
    "Tannourine Et-Tahta",
    "Thoum",
    "Toula El-Batroun",
    "Zaneh",
  ],
  "Becharré": [
    "Aabdine",
    "Bane",
    "Bazaaoun",
    "Bcharreh",
    "Beit Menzer",
    "Berhalioun",
    "Billa",
    "Blaouza",
    "Bqaa Kafra",
    "Bqerqacha",
    "Breissat",
    "Dimane",
    "Hadath Ej-Jebbeh",
    "Hadchit",
    "Hasroun",
    "Mazraat Aassaf",
    "Mazraat Bani Saab",
    "Mchaa Ej-Jibbé",
    "Moghr El-Ahoual",
    "Ouadi Qannoubine",
    "Qnat",
    "Qnayouer",
    "Tourza",
  ],
  "Békaa-Ouest": [
    "Aain Et-Tineh BG",
    "Aain Zebdeh",
    "Aammiq BG",
    "Aana",
    "Aaytanit",
    "Baaloul BG",
    "Bab Mareaa",
    "Bekaa Ouest",
    "Chebrqiyet Aammiq",
    "Dakoueh",
    "Deir Aain Ej-Jaouzeh",
    "Deir Tahniche",
    "Ghazzeh",
    "Haouch El-Harime",
    "Harimeh Es-Soughra",
    "Jazira BG",
    "Joubb Jannine",
    "Kafraiya BG",
    "Kamed El-Laouz",
    "Khiara",
    "Khiara El-Aatiqa",
    "Khirbet Qanafar",
    "Lala",
    "Libbaya BG",
    "Loussa",
    "Machghara",
    "Manara (Hammara) BG",
    "Mansoura BG",
    "Marj BG",
    "Maydoun",
    "Ouaqf BG",
    "Qaraaoun",
    "Qelaya",
    "Raouda (Istabel)",
    "Saghbine",
    "Sohmor",
    "Soltan Yacoub el Aradi",
    "Souairi",
    "Soultan Yaacoub Faouqa",
    "Tall Znoub",
    "Yohmor BG",
    "Zilaya",
  ],
  "Beyrouth": [
    "Achrafieh",
    "Achrafieh-Karm el Zeitoun",
    "Adlieh",
    "Ain el-Mreisseh",
    "Bachoura",
    "Badaro",
    "Beirut Central District",
    "Beyrouth",
    "Geitawi",
    "Gemayzé",
    "Kaskas",
    "Marfaa",
    "Mazraa",
    "Medawar",
    "Minet el-Hosn",
    "Monot",
    "Moussaytbeh",
    "Ras Beyrouth",
    "Remeil",
    "Rmeil",
    "Saifeh",
    "Saifi",
    "Sami el-Solh",
    "Sioufi",
    "Sodeco",
    "Sursock, St Nicolas",
    "Tabaris",
    "Tayyouneh",
    "Verdun",
    "Wadi Bou Jmil",
    "Zoukak el-Blatt",
  ],
  "Bint Jbeil": [
    "Aain Ibl",
    "Aaintaroun",
    "Aaita Ej-Jabal",
    "Aaynata Bent Jbayl",
    "Aayta Ech-Chaab",
    "Baraachit",
    "Beit Lif",
    "Beit Yahoun",
    "Bent Jbayl",
    "Borj qalaouiyeh",
    "Chaqra",
    "Debl",
    "Deir Ntar",
    "Froun",
    "Ghandouriyet Bent Jbayl",
    "Haddatha",
    "Hanine",
    "Haris",
    "Jmaijmeh",
    "Kafra Bant Jbayl",
    "Kfar Dounine",
    "Khirbet Selm",
    "Kounine",
    "Maroun Er-Ras",
    "Qalaouiyeh",
    "Qaouzah",
    "Qatmoun",
    "Rachaf",
    "Ramyet Bent Jbayl",
    "Rmaich",
    "Safad Al-Battikh",
    "Salhani",
    "Soultaniyet Bent Jbayl",
    "Srobbine",
    "Tibnine",
    "Tiri",
    "Yaroun",
    "Yater",
  ],
  "Chouf": [
    "Aain Ouzain",
    "Aain Qania",
    "Aain Zhalta",
    "Aainbal",
    "Aalmane Ech-Chouf",
    "Aammatour",
    "Aammiq Ech-Chouf",
    "Aanout",
    "Aathrine",
    "Baadarane",
    "Baaqline",
    "Baassir",
    "Barja",
    "Barouk",
    "Bater",
    "Batloun",
    "Bayqoun",
    "Bchtfine",
    "Beit Ed-Dine",
    "Benouati Ech-Chouf",
    "Biret Ech-Chouf",
    "Bkechtine Ouel Mcheiaa",
    "Bkifa Ech-Chouf",
    "Botmeh",
    "Bourjein",
    "Bqaiaa Ech-Chouf",
    "Brih",
    "Bsaba Ech-Chouf",
    "Chammis Ech-Chouf",
    "Chatra",
    "Chhim",
    "Chmaarine",
    "Chourit",
    "Dahr Ech-Chouf",
    "Dalhoun",
    "Damour",
    "Daraiya Ech-Chouf",
    "Deir  El-Moukhalles Ech-Chouf",
    "Deir Baba",
    "Deir Dourit",
    "Deir El-Qamar",
    "Deir Koucheh",
    "Dibbiyeh",
    "Dmit",
    "El Chouf",
    "Faouarat Jaafar",
    "Fraudis Ech-Chouf",
    "GHabet Jaafar",
    "Gharifeh",
    "Haret Jandal",
    "Hasrout",
    "Jadra",
    "Jahliyeh",
    "Jbaa Ech-Chouf",
    "Jdeidet Ech-Chouf",
    "Jiyeh",
    "Jleiliyeh",
    "Jmailiyeh",
    "Joun",
    "Kahlouniet Ech-Chouf",
    "Ketermaya",
    "Kfar Faqoud",
    "Kfar Hamal",
    "Kfar hay",
    "Kfar Him",
    "Kfar Nabrakh",
    "Kfar Niss",
    "Kfar Qatra",
    "Khereibet Ech-Chouf",
    "Khirbet Bisri",
    "Kneisset Ech-Chouf",
    "maaniyeh",
    "Maasser Beit Ed-Dine",
    "Maasser Ech-Chouf",
    "Majdalouna",
    "Majdel El-Meouch",
    "mazboud",
    "Mazmoura",
    "Mazraat Ech-Chouf",
    "Mazraat Ed-Douair",
    "Mazraat Es-Dahr",
    "Mechref",
    "Mghairiyeh Ech-Chouf",
    "Moughayret Ech-Chouf",
    "Moukhtara",
    "Mristi",
    "Mtolleh",
    "Naameh",
    "Niha El-Chouf",
    "Ouadi Abou Youssef",
    "Ouadi bnehlay",
    "Ouadi Ed-Deir",
    "Ouadi Es-Sitt",
    "Ouardaniyeh",
    "Ouarhaniyeh",
    "Qreiaa",
    "Rmeilé",
    "Rmeilet Ech-Chouf",
    "Semqaniyeh",
    "Sibline",
    "Sirjbal",
    "Zaarouriyeh",
  ],
  "Hasbaya": [
    "Aain Jarfa",
    "Aain Qinia",
    "Abou Qamha",
    "Bourghos",
    "Chebaa",
    "Chebaa Farms",
    "Chouaya Hasbaiya",
    "Dellafeh",
    "Fardis Hasbaiya",
    "Hasbaiya",
    "Hebbariyeh",
    "Kaoukaba Hasbaiya",
    "Kfar Chouba",
    "Kfar Hamam",
    "Kfayr Ez-Zait",
    "Khalouet Hasbaiya",
    "Khreibet Hasbaiya",
    "Majidiyeh Hasbaiya",
    "Marj Ez-Zouhour (Haouch El-Qinnaabeh)",
    "Meimes",
    "Meri",
    "Rachaiya El-Foukhar",
    "Salaiyeb",
  ],
  "Hermel": [
    "Charbine El-Hermel",
    "Hermel",
    "Hermel Jbab",
    "Maaysra El-Hermel",
    "Michaa Mrajhineh",
    "Ouadi Faara",
    "Ras Baalbek El Gharbi",
    "Ras Baalbek Ouadi Faara",
    "Zighrine",
  ],
  "Jbeil (Byblos)": [
    "Aabaydat",
    "Aain Ed-Delbeh Jbayl",
    "Aain El-Ghouaybeh",
    "Aain Jrain",
    "Aain Kfaa",
    "Aalita",
    "Aalmat Ech-Chamliyeh",
    "Aalmat Ej-Jnoubiyeh",
    "Aamchit",
    "Aaqoura",
    "Aarab El-Lahib",
    "Aarasta",
    "Adonis Jbayl",
    "Afqa Jbayl",
    "Amchit, Jbeil",
    "Bayzoun",
    "Bchille Jbayl",
    "Behdaydat",
    "Beit Habbaq",
    "Bejjeh",
    "Bekhaaz",
    "Berbara Jbayl",
    "Bichtlida",
    "Bintaael",
    "Birket Hjoula",
    "Blat Jbeil",
    "Bmehrayn",
    "Boulhos",
    "Brayj Jbayl",
    "Chamate",
    "Chikhane",
    "Chmout",
    "Eddeh Jbayl",
    "Ehmej",
    "Fatre",
    "Ferhet",
    "Fghal",
    "Frat",
    "Ghabat",
    "Ghalboun",
    "Gharzouz",
    "Ghofrine",
    "Habil",
    "Halate",
    "Haqel",
    "Hasrayel",
    "Hbaline",
    "Hboub",
    "Hdeine",
    "Hema Er-Rehban",
    "Hema Mar Maroun Aannaya",
    "Hjoula",
    "Hsarat",
    "Hsoun",
    "Jaj",
    "Janneh",
    "Jbayl",
    "Jeoddayel Jbayl",
    "Jlisseh",
    "Jouret El-Qattine",
    "Kafr",
    "Kfar Baal",
    "Kfar Kiddeh",
    "Kfar Mashoun",
    "Kfar Qouas",
    "Kfoun",
    "Kharbet Jbayl",
    "Laqlouq",
    "Lassa",
    "Lehfed",
    "Maad",
    "Majdel El-Aqoura",
    "Mar Sarkis",
    "Mastita",
    "Mayfouq",
    "Mazraat El-Maaden",
    "Mazraat Es Siyad",
    "Mchaneh",
    "Mghayreh Jbeil",
    "Michmich Jbayl",
    "Mounsef",
    "Nahr Ibrahim",
    "Qahmez",
    "Qartaba",
    "Qartaboun",
    "Qorqraiya",
    "Qottara Jbayl",
    "Ramout",
    "Ras Osta",
    "Rihanet Jbayl",
    "Saqi Richmaya",
    "Saqiet El-Khayt",
    "Sebrine",
    "Seraaiita",
    "Souanet Jbayl",
    "Tadmor",
    "Tartij",
    "Tourzaiya",
    "Yanouh Jbayl",
    "Zibdine Jbayl",
  ],
  "Jezzine": [
    "A'ain El-Mir (El Establ)",
    "Aaramta",
    "Aaray",
    "Aaychiyeh",
    "Aazour",
    "Anane",
    "Bayssour Jezzine",
    "Behbeh",
    "Benouati Jezzine",
    "Bhannine",
    "Bisri",
    "Bkassine",
    "Bouslaya",
    "Btedine El-Leqch",
    "Chbail",
    "Choualiq Jezzine",
    "Dahr Ed-Deir",
    "Deir El Qattine",
    "Demachqiyeh",
    "Ghabbatiyeh",
    "Harf Jezzine",
    "Hassaniyeh",
    "Haytouleh",
    "Haytoura",
    "Hidab",
    "Homsiyeh",
    "Jabal Toura",
    "Jarmaq",
    "Jensnaya",
    "Jernaya",
    "Jezzine",
    "Karkha",
    "Kfar Falous",
    "Kfar Houneh",
    "Kfar Jarra",
    "Lebaa",
    "Louayzet Jezzine",
    "Machmoucheh",
    "Mahmoudiyeh Jezzine",
    "Maknounet Jezzine",
    "Maraat Ouazaiyeh",
    "Mazraat",
    "Mazraat Daraya",
    "Mazraat El-Aarqoub",
    "Mazraat El-Mathane",
    "Mazraat Er-Rouhbane",
    "Mazraat Khallet Khazen",
    "Mazraat Louzid (Louayziyeh)",
    "Mazraat Qrouh",
    "Mazraat Tamra",
    "Mazraat Zighrine Jezzine",
    "Mharbiyeh",
    "Midane Jezzine",
    "Mjaydel Jezzine",
    "Mlikh",
    "Mrah El-Hbasse",
    "Ouadi Baanqoudaine",
    "Ouadi El-Laymoun",
    "Ouardiyeh",
    "Qabaa Jezzine",
    "Qatrani",
    "Qaytouleh",
    "Qtaleh Jezzine",
    "Rihane Jezzine",
    "Rimat",
    "Roum",
    "Roummanet",
    "Sabbah",
    "Sanaya",
    "Saydoun",
    "Sehjoud",
    "Sfaray",
    "Srayri",
    "Taaid",
    "Wadi Jezzine",
    "Zhilta",
  ],
  "Kesrouan": [
    "Aachqout",
    "Aain Ed-Delbeh Kesrouane",
    "Aain Er-Rihane",
    "Aajaltoun",
    "Aaqaibeh Kesrouane",
    "Aaramoun Kesrouane",
    "Aazra ouel Aazr",
    "Adma",
    "Adma Oua Dafine",
    "Adonis",
    "Aintoura Kesrouane",
    "Ajaltoun",
    "Balloune",
    "Ballouneh",
    "Batha",
    "Beqaata Aachqout",
    "Beqaata Kanaan",
    "Bizhel",
    "Bourj El-Ftouh",
    "Bqaatouta",
    "Bqaq Ed-Dine",
    "Bzoummar",
    "Chahtoul",
    "Chnanaair",
    "Chnanïr",
    "Chouane",
    "Daraaoun",
    "Daraiya Kesrouane",
    "Deir Baqlouch",
    "Dlebta",
    "Faraya",
    "Ghadir",
    "Ghbaleh Kesrouane",
    "Ghidras",
    "Ghineh",
    "Ghosta",
    "Harharaya",
    "Harissa Kesrouane",
    "Hayata",
    "Hrajel",
    "Hsayn",
    "Ighbeh",
    "Jaaita",
    "Jdaidet Ghazir",
    "Jounie Ghadir",
    "Jounie Haret Sakhr",
    "Jounieh",
    "Jounieh Sarba",
    "Jouret Bedrane",
    "Jouret E-Tourmos",
    "Jouret Mhad",
    "Kaslik",
    "Keserwan",
    "Kfar Dibiane",
    "Kfar Tay Kesrouane",
    "Kfar Yassine",
    "Kfour Kesrouane",
    "Kharayeb Nahr Ibrahim",
    "Maarab",
    "Maaysra Kesrouane",
    "Mayrouba",
    "Mazraat Er-Ras",
    "Mazraat Mrah El-Mir",
    "Mchaa El Ftouh",
    "Mchaa Faraya",
    "Mchaa Kfar Dibiane",
    "Mghayer",
    "Mradiyeh",
    "Nahr Ed-Dahab",
    "Nammoura Kesrouane",
    "Ouata El-Jaouz",
    "Ouata Sillam",
    "Qleiaat Kesrouane",
    "Raachine",
    "Rayfoun",
    "Safra Kesrouane",
    "Sahel Aalma",
    "Sahel Alma",
    "Shayleh Kesrouane",
    "Tabarja",
    "yahchouch",
    "Zaaitreh",
    "Zaitoun",
    "Zouk",
    "Zouk Mkayel",
    "Zouk Mousbeh",
  ],
  "Koura": [
    "Aaba",
    "Aafsdiq",
    "Ain Aakrine",
    "Amioun",
    "Badbhoun",
    "Barghoun",
    "Barsa",
    "Batroumine",
    "Bdebba",
    "Bechmizzine",
    "Bednayel El-Koura",
    "Bhabbouch El-Koura",
    "Bkeftine",
    "Bnehran",
    "Bqaiaa El-Koura",
    "Bsarma",
    "Btaaboura",
    "Bterram",
    "Btouratij",
    "Bziza",
    "Dar Baaechtar",
    "Dar Chmizzine",
    "Deddeh",
    "Deir El-Balamand",
    "El Koura",
    "Enfeh",
    "Fiaa",
    "Hraiche",
    "Ijdaabrine",
    "Kafraya El-Koura",
    "Kaftoun",
    "Kfar Aaqqa",
    "Kfar Hata El-Koura",
    "Kfar Hazir",
    "Kfar Kahel",
    "Kfar Saroun El-Koura",
    "Kousba",
    "Majdel el-Koura",
    "Metrit",
    "Nakhleh",
    "Qalhat",
    "Ras Masqa",
    "Rechdibbine",
    "Zakroun",
    "Zgharta El-Mtaouile",
  ],
  "Marjeyoun": [
    "Aadaysseh Marjaayoun",
    "Aadchit El-Qoussair",
    "Aain Aarab Marjaayoun",
    "Aalmane Marjaayoun",
    "Aamra",
    "Bany haiyane",
    "Blat Marjaayoun",
    "Blida",
    "Borj El-Moulouk",
    "Boueyda Marjaayoun",
    "Deir Mimas",
    "Deir Siriane",
    "Dibbine",
    "Houla",
    "Houra",
    "Ibl Es-Saqi",
    "Kfar Kila",
    "Khiyam Marjaayoun",
    "Majdel Selm",
    "Marjaayoun",
    "Markaba",
    "Mazraat Doumiat",
    "Mazraat Sarada",
    "Meiss Ej-Jabal",
    "Mhaibib",
    "Qabrikha",
    "Qantara",
    "Qlaiaa",
    "Rabb Et-Tlatine",
    "Saouanet Marjayoun",
    "Talloussa",
    "Taybet Matjaayoun",
    "Touline",
  ],
  "Matn": [
    "Aain Aar",
    "Aain El-Kharroubeh",
    "Aain El-Qabu",
    "Aain El-Qach",
    "Aain Es-Sindiane",
    "Aain es-Sofsaf El-Matn",
    "Aain Et-Teffaha",
    "Aain Ez-Zeitouneh",
    "Aain Saadeh",
    "Aamaret Chalhoub",
    "Aatchaneh",
    "Aayoun El-Matn",
    "Aayroun",
    "Abou Mizane",
    "Ain Aalaq",
    "Ain Aar",
    "Ain Alak",
    "Ain El Kharoube",
    "Ain Najem",
    "Ain Najm",
    "Ain Saade",
    "Ain Saadé",
    "Ain Saadé / Roumieh",
    "Aintoura",
    "Aintoura El-Matn",
    "Airoun",
    "Al Talleh",
    "Amaret Chalhoub",
    "Antelias",
    "Antélias",
    "Aoucar",
    "Awkar",
    "Aylout, Mansourieh",
    "Baabdat",
    "Baabdath",
    "Baouchrie",
    "Baouchrieh",
    "Baouchriyeh",
    "Baskinta",
    "Bauchrieh",
    "Bayada",
    "Beit Chabab",
    "Beit Ech-Chaar",
    "Beit El Chaar",
    "Beit el Kiko",
    "Beit El-Kekko",
    "Beit Meri",
    "Beit Misk",
    "BeitMery",
    "Belle Vue",
    "Bhersaf",
    "Biakout",
    "Bikfaya",
    "Bkennaya",
    "Bnabil",
    "Bolonia",
    "Bouar",
    "Bouchrieh",
    "Bourj Hammoud",
    "Bqennaya",
    "Broumana",
    "Broummana El-Matn",
    "Bsalim",
    "Bsifrine",
    "Bteghrine",
    "Byaqout",
    "Champville",
    "Chaouiyeh",
    "Charkié",
    "Chawieh",
    "Chouaya El-Matn",
    "Choueir",
    "Chrine",
    "Daher Sawan",
    "Dahr Es-Souane El-Matn",
    "Daoura",
    "Darb el Sekké",
    "Daychounieh",
    "Daychouniyeh",
    "Dbayeh",
    "Deir Chamra",
    "Deir el-Kalaa",
    "Deir Mar Aabda el Mchammar",
    "Deir mar Roukoz",
    "Deir Tamich",
    "Dékouané",
    "Dekouaneh",
    "Dekwané",
    "Dekwaneh-Mar Roukoz",
    "Dhour El Chouair",
    "Dik El-Mehdi",
    "DLEIBE",
    "Dora",
    "Douar",
    "Elissar",
    "Face Club Sportif de Delb",
    "Fanar",
    "Fraikeh",
    "Freiké",
    "Haï el Sanoubar",
    "Haklet Salameh",
    "Haret El-Ballane",
    "Haret Tahta",
    "Harik",
    "Hazmieh",
    "Hbous",
    "Hemlaya",
    "Himlaya",
    "Horch Tabet",
    "Itchaneh",
    "Jal el Dib",
    "Jall Ed-Did",
    "Jdaidet El-Matn",
    "Jdeide",
    "Jisr el Bacha",
    "Jisr el Wati",
    "Jouar El-Matn",
    "Jouret El-Ballout",
    "Jourit El Ballout",
    "Kafra",
    "Kalaa",
    "Kfar Aaqab",
    "Kfar Tay El-Matn",
    "Khenshara",
    "Khillet El-Mtain",
    "Khinchara",
    "Koneitré",
    "Kornet Chehwan",
    "Kornet el Hamra",
    "Maameltein",
    "Machraah El-Matn",
    "Majdel tarchich",
    "Majzoub",
    "Mansourieh",
    "Mansouriyet El-Matn",
    "Mar Boutros",
    "Mar Boutros Karm Et-Tine",
    "Mar Moussa",
    "Marjaba",
    "Masqa",
    "Maten",
    "Mayasseh",
    "Mazraat Deir Aaoukar",
    "Mazraat El-Hdaira",
    "Mazraat Yachouh",
    "Mchikha",
    "Menqlet Mezher",
    "Mezher",
    "Mhaidset Matn",
    "Mirna Chalouhi",
    "Miyassa",
    "Mkalles",
    "Monteverde",
    "Mrah Ghanem",
    "Mrouj",
    "Mtain",
    "Mtayleb",
    "Mtein",
    "Mzakkeh",
    "Nabay",
    "Naccache",
    "Nahr el Mot",
    "Naqqach",
    "New Jdeidé",
    "New Rawda",
    "North Maten",
    "Ouadi Chahine",
    "Ouadi El-Karm El-Matn",
    "Ouata El-Mrouj",
    "Picha",
    "Qaaqour",
    "Qannebet Salima",
    "Qennabet Broummana",
    "Qornet Chehouane",
    "Qornet El-Hamra",
    "Rabieh",
    "Raboué",
    "Rabwe",
    "Raouda",
    "Roumieh",
    "Sabtié",
    "Sabtiyé",
    "Sfeilet Bikfaya",
    "Sin el Fil",
    "Sinn El-Fil",
    "Zabbougha",
    "Zalk (Biakout)",
    "Zalka",
    "Zalqa",
    "Zaraaoun",
    "Zeghrine",
    "Zighrine El-Matn",
    "Zikrit",
    "Zone Verte",
    "Zouk El-Kharab",
  ],
  "Minieh-Danniyé": [
    "Aain Et-Tineh-Miniyeh",
    "Aasaymout",
    "Aassoun",
    "Aaymar",
    "Aazqai",
    "Bakhaaoun",
    "Bechehhara",
    "Bechnnata",
    "Beddaoui",
    "Behouaita",
    "Beit El-Faqs",
    "Beit Haouik",
    "Beit Zoud",
    "Borj El-Yahoudiyeh",
    "Bqaa Sefrine",
    "Bqarsouna",
    "Btermaz",
    "Debaael",
    "Deir Aammar",
    "Deir Nbouh",
    "El Minieh-Dennie",
    "Haouaret-Miniyeh",
    "Haql el Aazimeh",
    "Harf Es-Sayad",
    "Hazmiyet-Miniyeh",
    "Izal",
    "Jarjour",
    "Jayroun",
    "Kahf El-Malloul",
    "Karm El-Mohr",
    "Kfar Bibnine",
    "Kfar Chellane",
    "Kfar Habou",
    "Kharroub-Miniyeh",
    "Mazraat El-Kreme",
    "Mazraat Ketrane",
    "Merkebta",
    "Mimrine",
    "Minie",
    "Mrah Es-Sfire",
    "Mrah Es-Srayj",
    "Mrebbine",
    "Nabi Youcheaa",
    "Qarhaiya",
    "Qarne",
    "Qarsaita",
    "Qattineh-Miniyeh",
    "Qemmamine",
    "Qraine",
    "Raouda-Aadoua",
    "Rihaniyet-Miniyeh",
    "Sfireh",
    "Sir Ed-Danniyeh",
    "tarane",
    "Terbol-Miniyeh",
    "Zaghartaghrine",
    "Zouq Bhannine",
  ],
  "Nabatieh": [
    "Aabba",
    "Aadchit Ech-Chqif",
    "Aain Bou Souar",
    "Aain Qana",
    "Aali Et-Taher",
    "Aarab Salim",
    "Aazzi",
    "Ansar",
    "Arnoun",
    "Bfaroueh",
    "Braiqeaa",
    "Charqiyeh",
    "Choukine",
    "Deir Ez-Zahrani",
    "Douair En-Nabatiyeh",
    "Habbouch En-Nabatiyeh",
    "Hamra En-Nabattiyeh",
    "Harouf En-Nabatiyeh",
    "Hmaileh",
    "Houmine El-Faouqa",
    "Houmine Et-Tahta",
    "Jarjouaa",
    "Jbaa En-Nabatiyeh",
    "Jibchit",
    "Kfar Djal En-Nabatiyeh",
    "Kfar Roummane",
    "Kfar Sir",
    "Kfar Tibnit",
    "Kfarfila",
    "Kfour En-Nabatieh",
    "Mayfadoun",
    "Mazraat Bsaffour",
    "Mazraat Chalbaal",
    "Mazraat Dmoul",
    "Mazraat El-Bayad En-Nabatieh",
    "Mazraat Kfarjaouz",
    "Mazraat Qalaat El-Meis",
    "Mzaraat El-Khreibeh",
    "Nabatieh",
    "Nabatieh Et-Tahta",
    "Nabatiyeh El-Faouka",
    "Nmairiyeh",
    "Qaaqaaiyet Ej-Jisr",
    "Qsaibet En-Nabatiyeh",
    "Roumine",
    "Sarba En-Nabatieh",
    "Sir El-Gharbiyeh",
    "Toul",
    "Yohmor En-Nabatiyeh",
    "Zaoutar Ech-Charqiyeh",
    "Zaoutar El-Gharbiyeh",
    "Zefta",
    "Zibdine En-Nabatiyeh",
  ],
  "Rachaya": [
    "Aain Aarab Rachaiya",
    "Aain Aata",
    "Aain Rouha",
    "Aaqabet Rachaya",
    "Aayha",
    "Aayta El-Foukhar",
    "Bakka",
    "Bakkifac Rachaya",
    "Beit Lahia",
    "Biret Rachaiya",
    "Dahr El-Ahmar",
    "Deir El-Aachayer",
    "Haouch El Qinnabeh Rachaiya",
    "Helouet Rachaiya",
    "Kaoukaba Bou Arab",
    "Kfar Denis",
    "Kfar Lichki",
    "Kfar Qouq",
    "Khirbet Rouha",
    "Majdel Balhis",
    "Mazraat Deir al-Ashayer",
    "Mdoukha",
    "Mhaiydseh Rachaiya",
    "Nabi Safa",
    "Rachaiya",
    "Rachaya",
    "Rafid Rachaiya",
    "Selsata (Mazraat Deir El-Aachaiyer)",
    "Tannoura",
    "Yanta",
  ],
  "Saïda": [
    "AAbra Saida",
    "Aadloun",
    "Aadoussiyeh",
    "Aain Ed-Delb",
    "Aanqoun",
    "Aaqtanit",
    "Aarab Ej-Jall",
    "Aarab Tabbaya",
    "Arzai",
    "Babliyeh",
    "Berti",
    "Bissariyeh",
    "Bnaafoul",
    "Bqosta",
    "Bramiyeh",
    "Daoudiyeh",
    "Darb Es-Sim",
    "Erkay",
    "Ghassaniyeh",
    "Ghaziyeh",
    "Hajjeh",
    "Haret Saida",
    "Hartiyeh",
    "Hlaliyeh Saida",
    "Insariyeh",
    "Jazira Saida",
    "Kaoutariyet Es-Siyad",
    "Kfar Beit",
    "Kfar Chellal",
    "Kfar Hatta Saida",
    "Kfar Melki Saida",
    "Khartoum",
    "Khayayeb Saida",
    "Khirbet Ed-Douair Saida",
    "Khirbet El-Bassal",
    "Khzaiz",
    "Loubieh",
    "Maamriyeh",
    "Maghdoucheh",
    "Majdelyoun",
    "Matariyet Ech-Choumar",
    "Mazraat 'Mseileh",
    "Mazraat 'Snaiber",
    "Mazraat Aarab Soukkar",
    "Mazraat Deir Taqla",
    "Mazraat El Yahoudiyeh (Aaitaniyeh)",
    "Mazraat El-Houssainiyeh",
    "Mazraat El-Mhaydaleh",
    "Mazraat Jamjim",
    "Mazraat Kaoutariyet Er-Riz",
    "Mazraat Kfar Beda",
    "Mazraat Oussamiyat",
    "Mazraat Sari",
    "Mazraat Sinai",
    "Merouaniyeh",
    "Miyeh ou Miyeh",
    "Mtayriyeh",
    "Mzaraat El-Ouasta",
    "Najjariyeh",
    "Qaaqaiyet Es-Snaoubar",
    "Qennarit",
    "Qraiyet Saida",
    "Saida Ed-Dekermane",
    "Saida El-Oustani",
    "Saida El-Qadimeh",
    "Saida Kefraya",
    "Saksakiyeh",
    "Salhiyet Saida",
    "Sarafand",
    "Sfenta",
    "Tanbourit",
    "Tebna",
    "Teffahta",
    "Zaghdraiya",
    "Zeita",
    "Zrariyeh",
  ],
  "Sour (Tyr)": [
    "Aabbassiyet Sour",
    "Aain Abou Abdallah",
    "Aain Baal",
    "Aaiyeh",
    "Aalma Ech-Chaab",
    "Aaytit",
    "Aaziyeh",
    "Abou Chech",
    "Arzoun",
    "Bafliyeh",
    "Barich",
    "Batoulay",
    "Bazouriyeh",
    "Bedias",
    "Bestiyat",
    "Biyad",
    "Borj Ech-Chemali",
    "Borj En-Naqoura",
    "Borj Rahhal",
    "Boustane",
    "Btaychiyeh",
    "Chaaitiyeh",
    "Chamaa",
    "Chehabiyeh",
    "Chehour",
    "Chihine",
    "Debaal Sour",
    "Deir Aames",
    "Deir Kifa",
    "Deir Qanoun El-Aain",
    "Deir Qanoun En-Nahr",
    "Derdaghaiya",
    "Dhayra",
    "Halloussiyeh",
    "Hamoul",
    "Hanaouay",
    "Henniyeh",
    "Hmairi Sour",
    "Iskandarouna Sour",
    "Jbal El-Botm",
    "Jennata",
    "Jibbayn",
    "Jijim",
    "Jouaiya",
    "Kneisset Sour",
    "Maarakeh",
    "Maaroub",
    "Majdel",
    "Majdelzoun",
    "Mansouri Sour",
    "Marnba",
    "Mazraat Ez-Zalloutiyeh",
    "Mazraat Mechref",
    "Mazraat Tayr Semhat",
    "Merouahine",
    "Mheilib",
    "Neftakhiyeh",
    "Niha Sour",
    "Ouadi Jilo",
    "Qana",
    "Qlaileh Sour",
    "Recheknanay",
    "Rmadiyeh",
    "Sadiqine",
    "Selaa Sour",
    "Sour",
    "Srifa",
    "Tayr Debbeh",
    "Tayr Falsay",
    "Tayr Harfa",
    "Touayri",
    "Toura",
    "Yanouh Sour",
    "Yarine",
    "Zebqine",
  ],
  "Tripoli": [
    "Mina Jardin",
    "Mina N:1",
    "Mina N:2",
    "Mina N:3",
    "Qalamoun",
    "Trablous El Hadid",
    "Trablous El Mhatra",
    "Trablous El-Haddadine, El-Hadid, El-Mharta",
    "Trablous El-Qobbe",
    "Trablous En-Nouri",
    "Trablous Er-Remmaneh",
    "Trablous Es-Souayqa",
    "Trablous et Tabbaneh",
    "Trablous Et-Tell",
    "Trablous Ez-Zahrieh",
    "Trablous Ez-Zeitoun",
    "Trablous jardins",
    "Tripoli",
  ],
  "Zahlé": [
    "Aain Kfar Zabad",
    "Aali En-Nahri",
    "Aanjar (Haouch Moussa)",
    "Ablah",
    "Barr Elias",
    "Bouarej",
    "Chebrqiyet Tabet",
    "Chtaura",
    "Dalhamiyet Zahleh",
    "Deir El-Ghazal",
    "Fourzol",
    "Haouch El-Aamara",
    "Haouch El-Ghanam",
    "Haouch Es-Siyadeh",
    "Haouch Hala",
    "Haouch Mandara",
    "Haouch Qayssar",
    "Hazerta",
    "Hoshmosh",
    "Jdita",
    "Kfarzabad",
    "Ksara",
    "Majdel Aanjar",
    "Makseh",
    "Massa",
    "Mazraat Er-Remtaniyeh",
    "Mrayjat Zahleh",
    "Mzaraat Zahlé",
    "Mzaraat Zahleh",
    "Nabi Ayla",
    "Nasriyet Rizk",
    "Nasriyet Zahleh",
    "Niha Zahleh",
    "Ouadi Ed-Delm",
    "Ouadi El-Aarayech",
    "Qaa Er-Rim",
    "Qabb Elias",
    "Qoussaya",
    "Raait",
    "Riyaq",
    "Saadnayel",
    "Taalbaya",
    "Taanayel",
    "Tcheflik Eddé Haouch",
    "Tcheflik Qiqano",
    "Tell El-Akhdar",
    "Terbol Zahleh",
    "Touaite Zahleh",
    "Zahlé Haouch El-Oumara Aradi",
    "Zahlé Mar Antonios",
    "Zahlé Mar Elias",
    "Zahlé Mar Gerges",
    "Zahlé Saydet En-Najat",
    "Zahleh Aradi",
    "Zahleh El-Berbara",
    "Zahleh El-Maallaqa",
    "Zahleh El-Midane",
    "Zahleh Er-Rassiyeh",
    "Zahleh Haouch El-Oumara",
    "Zahleh Haouch Ez-Zaraane",
    "Zahleh Maallaqa Aradi",
    "Zebdoul",
  ],
  "Zgharta": [
    "Aachach",
    "Aalma",
    "Aarbet Qozhaiya",
    "Aardat",
    "Aarjis",
    "Aintourine",
    "Arde",
    "Asnoun",
    "Ayto",
    "Bchannine",
    "Beslouqit",
    "Bhairet Toula",
    "Bnechaai",
    "Boussit",
    "Bsebaal",
    "Danha",
    "Daraiya Zgharta",
    "Deir Jdeide",
    "Ehden",
    "Hailan",
    "Hariq Zgharta",
    "Houakir",
    "Hraiqis",
    "Iaal",
    "Ijbaa",
    "Karm Saddeh",
    "Kfarchakhna",
    "Kfardlaqous",
    "Kfarfou",
    "Kfarhata Zgharta",
    "Kfarhoura",
    "Kfarsghab",
    "Kfaryachit",
    "Kfarzaina",
    "Khaldiyeh",
    "Mazraat Ajbeaa",
    "Mazraat Et-Teffah",
    "Mazraat Jnaid",
    "Mejdlaiya Zgharta",
    "Miriata",
    "Miziara",
    "Morh Kfarsghab",
    "Mzraat Kefraya",
    "Qarah Bach",
    "Rachaaine",
    "Ras Kifa",
    "Sakhra",
    "Sebaal Zgharta",
    "Seraal",
    "Tallet Zgharta",
    "Toula Zgharta",
    "Zgharta",
  ],
};

// ─── Resolver ─────────────────────────────────────────────────────────

/**
 * For a given preset field type, return its option list. Returns null for
 * non-preset types (the caller falls back to the field's manually-defined
 * `options` array).
 */
export function presetOptionsForType(type: string): string[] | null {
  switch (type) {
    case "country":
      return COUNTRIES_FR;
    case "nationality":
      return NATIONALITIES_FR;
    case "lebanon_region":
      return LEBANON_REGIONS_FR;
    default:
      return null;
  }
}
